### ISSUE TITLE
Feature: Header navigation

### ISSUE THREAD

**Issue by erlend-sh** [erlend-sh/learndiscourse#10]
TODO: 
- [x] Header navigation that mimics that of Discourse.org.
- [x] Change the Discourse logo to our own (same as Favicon)
- [x] clean away any "fake" navigation elements (file for logo is in PM)
- <del>center the navbar (screenshots below)</del>

Screenshot:
![http://i.imgur.com/S6iPGUZ.png](http://i.imgur.com/S6iPGUZ.png)

Discourse.org
![http://i.imgur.com/eMHD6yj.png](http://i.imgur.com/eMHD6yj.png)

**Comment by ghost** [comment]
Please work on #13 as well!

**Comment by erlend-sh** [comment]
Changed logo and removed redundant nav elements (simply edited header.html, assuming that's all there is to it.)

@nahtnam Didn't consider this before, but if we center it now that it only has one nav-element it'll probably look really weird.
