### ISSUE TITLE
Feature: Table of Contents

### ISSUE THREAD

**Issue by erlend-sh** [erlend-sh/learndiscourse#12]
Table of contents widget/sidebar for articles.

Config-based:
http://www.seanbuscay.com/blog/jekyll-toc-markdown/

Liquid-based:
https://github.com/dafi/jekyll-toc-generator

JavaScript-based:
https://github.com/ghiculescu/jekyll-table-of-contents

**Comment by erickguan** [comment]
Liquid filter is impossible if we are using github pages. A modified version of jekyll-table-of-contents is used. Some incorrect header levels will show weird results. I am not sure whether it's worthwhile to fix it or modified the script to compromise.

**Comment by erlend-sh** [comment]
It's a tentative issue anyhow, so it's low priority. We should chat :D See you on Gitter?
