### ISSUE TITLE
Center Navbar

### ISSUE THREAD

**Issue by ghost** [erlend-sh/learndiscourse#13]
Hey!

It would look a lot better if the navbar at the top is centered like @ discourse.org

Screenshot:
![http://i.imgur.com/S6iPGUZ.png](http://i.imgur.com/S6iPGUZ.png)

Discourse.org
![http://i.imgur.com/eMHD6yj.png](http://i.imgur.com/eMHD6yj.png)

**Comment by erlend-sh** [comment]
Yeh, makes sense. Could you please post this as an add-on to #10 though? We don't need two issues to keep track of the top navigation.
