### ISSUE TITLE
Images Broken

### ISSUE THREAD

**Issue by ghost** [erlend-sh/learndiscourse#16]
http://learndiscourse.org/configure-automatic-backups-for-discourse/

Images are pretty much broken everywhere.

**Comment by erlend-sh** [comment]
@fantasticfears How come we have img links like `<img src="/uploads/default/4451/efe294bfd5f02d13.png" width="690" height="64">`?

In the original (raw) version of [Configure automatic backups for Discourse](https://meta.discourse.org/raw/14855), image links look like this:

`<img src="//discourse-meta.s3-us-west-1.amazonaws.com/original/2X/c/cdebee5626392e3869cba8a3cddc977822f951ff.png" width="690" height="64">`

They're absolute links, so we don't even have to rewrite the URL or make local copies. If there are no objections, I'll manually "re-import" articles with images in them to use these absolute URLs.

**Comment by erickguan** [comment]
We should add assets to the repo instead of using Meta S3 assets.

**Comment by erlend-sh** [comment]
Yes, I agree. But for now we don't know for sure what the writing workflow will be like for doc contributors, so as far as v1 is concerned, I'm fine with simply linking to Meta's  CDN.

**Comment by erickguan** [comment]
Well, it's kinda hard right now. I can re-import the docs from Meta Discourse, but it will lose the subsection meta attr since there isn't a mapping between the original link to the S3 link.

**Comment by erickguan** [comment]
Ooops, forget to fix this...
