### ISSUE TITLE
Footer Broken?

### ISSUE THREAD

**Issue by ghost** [erlend-sh/learndiscourse#17]
Hey!

When you go to a post like http://learndiscourse.org/trust-levels/  the footer overlaps the content: http://i.imgur.com/qxtXBfS.png

Using latest chrome on Ubuntu.

**Comment by mcwumbly** [comment]
look like that happened here:

https://github.com/nahtnam/learndiscourse/commit/99b1ee6e965724c1acb6c5ba8cd4206de1c579bc#diff-2c19d9859b055d0302043d0fa2833e3fR22

I think @fantasticfears was trying to make sure that the footer shows on the main page when that was added back in.

I'll have a fix shortly.
