### ISSUE TITLE
Import script should include source link pointing to original forum post

### ISSUE THREAD

**Issue by erlend-sh** [erlend-sh/learndiscourse#18]
This script:

https://github.com/nahtnam/learndiscourse/blob/gh-pages/tools/doc_section_maintainer.rb

Could be modified to include a subtle "Source: {this-linked-article}" at the top or bottom of every article.
- It makes it even clearer for first-time visitors how this site actually works (as in, don't worry about the duplicate content, we've got it under control!)
- Prospective contributors can easily find the source article they want to make edits to.

**Comment by erickguan** [comment]
done :)

**Comment by erlend-sh** [comment]
Sweet. Perhaps the script should automatically wrap the source text in `<small>` tags or something so that it doesn't take away from the main article?

**Comment by erickguan** [comment]
Done.

**Comment by erlend-sh** [comment]
_@SamSaffron said:_

> Can we make all the links to "source" hyperlink back to meta?

I think that's a good idea. What do you think @fantasticfears ? The standard blue might make it stand out too much though. Maybe we can experiment with custom link styling, e.g. just bold, or an underline.

**Comment by erickguan** [comment]
Done.
