### ISSUE TITLE
Use default Discourse colors for section headers

### ISSUE THREAD

**Issue by erlend-sh** [erlend-sh/learndiscourse#19]
I love the new flat-color headers!

<img width="782" alt="screen shot 2015-08-03 at 12 49 44" src="https://cloud.githubusercontent.com/assets/583842/9036358/2d4e3d86-39e1-11e5-9473-adad8cc9bdcc.png">

I'd just like to suggest that we use the default, recurring colors that you see on pages like https://payments.discourse.org/buy/. Meaning:

User; Green: `#1bb058`
Moderator; Orange: `#f9a41a`
Admin; Red: `#d13138`
Designer; Blue: `#29abe2`
Sysadmin; Purple: `#9E34EC`(new)
Developer; Black: `#1b1f20`

Examples:

<img width="782" alt="admins-newcolor" src="https://cloud.githubusercontent.com/assets/583842/9036700/16e2a674-39e4-11e5-9621-72365c2abf26.png">

<img width="821" alt="user-newcolor" src="https://cloud.githubusercontent.com/assets/583842/9036726/4b24a856-39e4-11e5-9f40-e257021cedc3.png">

**Comment by ghost** [comment]
+1

**Comment by ghost** [comment]
Any idea what branch this is on?

**Comment by erickguan** [comment]
All colors updated :)
@nahtnam All operated in gh-pages
