### ISSUE TITLE
Feature: Breadcrumb

### ISSUE THREAD

**Issue by erlend-sh** [erlend-sh/learndiscourse#2]
Simple [breadcrumbs navigation](http://stackoverflow.com/questions/9612235/what-are-some-good-ways-to-implement-breadcrumbs-on-a-jekyll-site).

**Comment by erlend-sh** [comment]
So apparently work on this has already started. Looking great @fantasticfears!

<img width="782" alt="screen shot 2015-08-03 at 12 49 44" src="https://cloud.githubusercontent.com/assets/583842/9036078/4566a3c0-39de-11e5-8217-a981fb011735.png">

Feel free to move this to Milestone v1 if you intend to implement this everywhere.

**Comment by erickguan** [comment]
I think breadcrumb woule be only show on the doc page. So can we call it a day on this?

**Comment by erlend-sh** [comment]
Yeah, we can leave it at that, and see where user feedback takes us later.
