### ISSUE TITLE
Long article titles are not text-wrapped

### ISSUE THREAD

**Issue by erlend-sh** [erlend-sh/learndiscourse#22]
Known issue. Just adding adding here for posterity.

<img width="1093" alt="screen shot 2015-08-08 at 15 39 32" src="https://cloud.githubusercontent.com/assets/583842/9150882/716d6fc6-3dee-11e5-9700-e2f146d1b4ae.png">

**Comment by erickguan** [comment]
Could you try again? Some code just kicked in as you create this issue :)

**Comment by erlend-sh** [comment]
:+1:
