### ISSUE TITLE
Import docs from remote GitHub repository

### ISSUE THREAD

**Issue by erlend-sh** [erlend-sh/learndiscourse#24]
We need a first take on importing docs from a GitHub repository, specifically the Discourse repo's docs folder:

https://github.com/discourse/discourse/tree/master/docs

It might even be possible to do a direct repoA-->repoB transfer using the GitHub API, but I'd rather put that on hold for now, since that would be a very different workflow from what we've established thus far.

If it's easily doable, I think a good first take on this would be to incorporate "GitHub folder download" into `doc_section_maintainer.rb`, and we'll make it part of our current workflow.

**Comment by erlend-sh** [comment]
Works! Couple things though:

Won't work as simple link. Requires the special formatting:

```
- 
 url: https://...
 weight: 200
```

Also, this one link doesn't work:

```
https://github.com/discourse/discourse_docker/blob/master/README.md
```

```
Downloading url: [1/12] https://github.com/discourse/discourse_docker/blob/master/README.md
/Users/erlend/Repos/learndiscourse/tools/doc_section_maintainer.rb:101:in `slug': undefined method `[]' for nil:NilClass (NoMethodError)
        from /Users/erlend/Repos/learndiscourse/tools/doc_section_maintainer.rb:191:in `block in get_docs'
        from /Users/erlend/Repos/learndiscourse/tools/doc_section_maintainer.rb:179:in `each'
        from /Users/erlend/Repos/learndiscourse/tools/doc_section_maintainer.rb:179:in `get_docs'
        from /Users/erlend/Repos/learndiscourse/tools/doc_section_maintainer.rb:173:in `block in get_subsection'
        from /Users/erlend/Repos/learndiscourse/tools/doc_section_maintainer.rb:171:in `each'
        from /Users/erlend/Repos/learndiscourse/tools/doc_section_maintainer.rb:171:in `get_subsection'
        from /Users/erlend/Repos/learndiscourse/tools/doc_section_maintainer.rb:164:in `block in get_portal'
        from /Users/erlend/Repos/learndiscourse/tools/doc_section_maintainer.rb:162:in `each'
        from /Users/erlend/Repos/learndiscourse/tools/doc_section_maintainer.rb:162:in `get_portal'
        from /Users/erlend/Repos/learndiscourse/tools/doc_section_maintainer.rb:244:in `execute'
        from /Users/erlend/Repos/learndiscourse/tools/doc_section_maintainer.rb:259:in `<main>'
```

I guess it's because of the underscore?

---

Oh, and Source links are incorrect:

http://learndiscourse.org/development-osx-native/

Main problem is of course that it's using the API link, but it seems like it might also be hitting a max-length and gets cut off? This could also become a problem.

**Comment by erickguan** [comment]
Fixed.
- It's working for a simple link. I can't repro the problem. Maybe it's because related bug. Now bugs are fixed.
- I added two attr in the `doc_list.yml` you can use. One is `extract_title`, for Github doc, the script will try to extract the title from the first title in the file. Set it as false to turn off this behaviour. The other is `title`, which allows you to overwrite title as you like. Otherwise, it will generate from the file name when importing from GitHub. Try to use them in the same time :)

**Comment by erlend-sh** [comment]
Got it! :+1:
