### ISSUE TITLE
Better site analytics

### ISSUE THREAD

**Issue by erlend-sh** [erlend-sh/learndiscourse#25]
GitHub has its [own analytics](https://github.com/nahtnam/learndiscourse/graphs/traffic), but I don't think this sufficiently covers GitHub Pages / Jekyll.

Google Analytics comes first to mind of course, but I'm open to (free) suggestions.

The process [described here](http://joshualande.com/jekyll-github-pages-poole/) seems straight forward enough.

> First, I had to register my website through Google Analytics. Google gave me this javascript tracking code to embed on every website: (...)

This is ours:

```
<script>
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

  ga('create', 'UA-66145978-1', 'auto');
  ga('send', 'pageview');

</script>
```

> I put this code in the file _includes/google_analytics.html Finally, I included this tracking code on all of the pages of my website by modifying the file _layouts/default.html to include the line:

```
{% include google_analytics.html %}
```

**Comment by ghost** [comment]
Why not use cloudflare for analytics as well? We can get some free SSL at
the same time...

**Comment by erlend-sh** [comment]
Oh, I didn't know cloudflare had analytics. Sure, we can give that a try. Wanna implement it? :grinning:

**Comment by ghost** [comment]
Sure. Would require some nameserver changes. I dont think cloudflare lets
multiple people have permissions to a single domain so we will probably
have to create a shared account.

Should we get learndiscourse@gmail.com and then share the password VIA
https://keybase.io/nahtnam (encrypted) or something?

**Comment by erlend-sh** [comment]
Hmmm, right, the lack of shared accounts is a bit annoying.

Since nameserver changes are required I'd like to give @fantasticfears and @mcwumbly a chance to chime in on this one before we move forward with that kind of change.

I wouldn't mind testing the simple Google Analytics setup in the meantime though. I've sent you an invite to our GA account.

**Comment by ghost** [comment]
Didnt get the invite. :(

**Comment by erlend-sh** [comment]
Hmm. I tried sending you another mail now. In any case, the tracking code pasted above should be all you need to get it working. You just won't be able to confirm that it's working without the login.

**Comment by erickguan** [comment]
I didn't receive the invite either. (see GH profile for email)

And the GA code was applied.

**Comment by ghost** [comment]
There you go, finally got it :P
