### ISSUE TITLE
Code blocks are not rendered correctly

### ISSUE THREAD

**Issue by jmay** [erlend-sh/learndiscourse#26]
See http://learndiscourse.org/install-a-plugin/

Newlines in the code block are collapsed. Something is different in how the markdown is converted on Discourse vs Jekyll.

**Comment by jmay** [comment]
CSS needs something like `white-space: pre;`. And Kramdown might not handle syntax highlighting in fenced code blocks?

**Comment by ghost** [comment]
Fixed but still needs syntax highlighting and some styling though. Maybe create another issue for that?
