### ISSUE TITLE
Add syntax highlighting and styling for code blocks.

### ISSUE THREAD

**Issue by ghost** [erlend-sh/learndiscourse#27]
Hey!

I just pushed 944dd9488cda80eb7ed94a53e9eefe85da7afc25 to fix #26

This fix adds codeblocks but it doesnt style them and add syntax highlighting.

Thanks.

**Comment by erlend-sh** [comment]
Cool, seems to work :+1: 

Just as an added note, Our base theme, Lanyon, supports syntax highlighting out of the box, but it appears to only do it with the liquid tags `{% highlight js %}` and `{% endhighlight %}`

https://raw.githubusercontent.com/poole/lanyon/master/_posts/2014-01-01-example-content.md

**Comment by erlend-sh** [comment]
I noticed another case where some code blocks have disappeared:

https://meta.discourse.org/t/beginners-guide-to-creating-discourse-plugins-part-2-plugin-outlets/31001

On our end:

http://learndiscourse.org/beginners-guide-to-creating-discourse-plugins-part-2-plugin-outlets/

<img width="841" alt="screen shot 2015-08-20 at 08 59 33" src="https://cloud.githubusercontent.com/assets/583842/9377485/ce2d4842-4719-11e5-9c88-52626359d37e.png">

**Comment by ghost** [comment]
Good catch.

This is really weird. Only handlebars code isnt being rendered.

Are we using handlebars in the site or something?
