### ISSUE TITLE
Generate portal templates in the importer script

### ISSUE THREAD

**Issue by erlend-sh** [erlend-sh/learndiscourse#28]
Since the portal pages never require changes, they might as well be automatically created by the import script, because:

> the thing is, at least on Mac, if I move the entire _en file from tools to the root folder, files like administrators.html gets deleted. so to avoid that I have to move one sub-folder at a time.

**Comment by erickguan** [comment]
I think there is a better way. You can use `cp -r` to overwrite them. Is it good to you?

**Comment by erlend-sh** [comment]
Cool, I think you're right! This seems to work:

```
cp -R /Users/erlend/Repos/learndiscourse/tools/export/_en /Users/erlend/Repos/learndiscourse
```

Had to do [a bit of reading](http://www.macworld.com/article/2080814/master-the-command-line-copying-and-moving-files.html) to figure out exactly what you were talking about ;)

**Comment by erlend-sh** [comment]
Oh, there's still one problem with this method though. Say for instance a source topic is renamed. This actually happened recently:

<img width="986" alt="screen shot 2015-09-12 at 15 56 35" src="https://cloud.githubusercontent.com/assets/583842/9831840/ef71a03e-5966-11e5-89a6-1bc82e8a5389.png">

```
https://meta.discourse.org/t/using-discourse-api/17587
```

Was renamed to:

```
https://meta.discourse.org/t/using-the-discourse-api-ruby-gem/17587
```

Which means our static page

```
http://learndiscourse.org/using-discourse-api/
```

Should be deprecated in favour of the new

```
http://learndiscourse.org/using-the-discourse-api-ruby-gem/
```

_However_, if I just use `cp -R`, the deprecated article will not be removed, and we'll end up with two nearly identical articles.

**Comment by erickguan** [comment]
> Had to do a bit of reading to figure out exactly what you were talking about ;)

I don't even notice I am familiar with command line :P

For rename pages, two choices ahead:
1. Manual removal. If we have doc only on available on our part, it can be removed accidentally.
2. I'll put the templates anyway. It's easy
