### ISSUE TITLE
Feature: Sidebar

### ISSUE THREAD

**Issue by erlend-sh** [erlend-sh/learndiscourse#3]
Left-hand sidebar navigation for easy access to articles from beginning to end.

**Comment by erlend-sh** [comment]
Duplicate of #1 . Now how do I delete this issue...

**Comment by ghost** [comment]
You dont. Best you can do it close it and lock it.

**Comment by erlend-sh** [comment]
:crying_cat_face: Aw well. I guess it doesn't disrupt anything now that I changed the labels and removed the milestone.
