### ISSUE TITLE
Keep track of redirects

### ISSUE THREAD

**Issue by erlend-sh** [erlend-sh/learndiscourse#33]
Should be doable with the [default redirection strategy](https://help.github.com/articles/redirects-on-github-pages/) incorporated into GitHub pages. Just need to add frontmatter for `redirect_from: "/foo"` in the `doc_list.yml`.

If not, there are some options:
- https://github.com/nquinlan/jekyll-pageless-redirects
- https://github.com/mfenner/jekyll-travis

**Comment by erickguan** [comment]
Simply adding a `redirect_from` as we do with `weight`
