### ISSUE TITLE
Dynamic article search

### ISSUE THREAD

**Issue by erlend-sh** [erlend-sh/learndiscourse#34]
WIP

I can think of 3 different approaches to search:
### JavaScript search

Lunr
### Discourse API search

This is the one that appeals to me the most, but it's also the funkiest. My thinking is this:
1. Tap into the meta.discourse.org API with client-side JavaScript (similar to lunr.js at this stage)
2. Search exclusively for topics in the How-to category
3. [Generate a page](http://benhowdle.im/creating-a-dynamic-search-page-for-your-jekyll-blog.html) showing the results.
4. Replace the meta.discourse.org/\* links with learndiscourse.org/\* links.

Caveat 1: Since Discourse doesn't support filtering with more than one category at a time, all doc articles would have to live in one single category. But this is something we want anyways.

Caveat 2: Articles from GitHub will not be searched. One way around this would be to automatically (or manually) mirror a GitHub article to a Meta topic (which could optionally be unlisted). This would also make the import script simpler, since the import could now be pulling exclusively from Meta, the way it worked originally.

**Comment by erickguan** [comment]
Javascript search could be a better solution.
1. Data file comes from jekyll building process.
2. No new web request need to be handled.
3. Discourse API search seems an additional feature comparing to the search function of the learndiscourse site. Without considering building Meta API as an process, there is no big caveat then.
4. There is not a good way to stylize the custom google search. Nevertheless, it's a plus.

**Comment by erlend-sh** [comment]
Yeah I'm also in favour of JavaScript search except: It bothers me that users would be getting different search results based on where they're searching: learndiscourse.org or Meta. That's why I started pondering the "API Search" solution, but it's kind of ugly.

I wonder how similar Discourse's search is to lunr.js (which afaik is the best option available for JS-based search on Jekyll).

**Comment by erickguan** [comment]
Remember the learndiscourse idea is to be the documentation site. If it's good enough, it's possible to remove the original documentation from Meta. Meta is the place the customer looking for support. Therefore, I don't see the conflicts. However, it will confuse a lot of guys if they are not sure what they are looking for.

Only at a glance, `lunr.js` needs an index file to power the searching functionality which means the index file should be downloaded when searching. Discourse runs the query on its database all over the site under different combination of query terms and limitations (e.g. on this topic, searching this user).

I am not sure whether I explained your problem...If unclear, plz point out

**Comment by erickguan** [comment]
Google Custom Search is used for v2.
